DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  image TEXT,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  countryId INTEGER NOT NULL,
  bio TEXT
);